name: Check Microsoft E5 Expiry

on:
  schedule:
    # 每周一 02:30 UTC 运行（北京时间 10:30 AM）
    - cron: '30 2 * * 1'
  workflow_dispatch: # 允许手动触发

jobs:
  check-expiry:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu runner

    steps:
    # Step 1: 检出代码
    - name: Checkout repository code
      uses: actions/checkout@v4 # 检查出代码，包括 Python 脚本

    # Step 2: 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # 使用 Python 3.10

    # Step 3: 安装系统依赖项（Chrome 和 ChromeDriver）
    - name: Install system dependencies (Chrome & ChromeDriver)
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        # 验证是否正确安装
        google-chrome --version
        chromedriver --version

    # Step 4: 安装 Python 依赖项
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        # 如果使用 sendNotify.py，安装其他必要依赖项
        # pip install requests 

    # Step 5: 运行 E5 检查脚本
    - name: Run E5 Expiry Check Script
      env:
        # 重要：从 GitHub Secrets 获取账号字符串
        MS_E5_ACCOUNTS: ${{ secrets.MS_E5_ACCOUNTS }} 
        # 如果使用 sendNotify.py，添加相应的 Secrets
        # PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }} 
        # TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        # TG_USER_ID: ${{ secrets.TG_USER_ID }}
      run: python check_e5_expiry.py # 确保脚本名称为 check_e5_expiry.py

    # Step 6: 上传调试截图（仅在失败时运行）
    - name: Upload Debug Screenshots on Failure
      if: failure() # 仅在前面的步骤失败时运行
      uses: actions/upload-artifact@v3
      with:
        name: error-screenshots
        path: ./*.png # 上传当前目录下的所有 PNG 文件（假设截图保存在当前目录）
